import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Providers } from "@/components/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        {process.env.NEXT_PUBLIC_CONVEX_URL?.trim() ? (
          <ConvexAuthNextjsServerProvider>
            <Providers>
              <ConvexClientProvider>
                {children}
              </ConvexClientProvider>
            </Providers>
          </ConvexAuthNextjsServerProvider>
        ) : (
          <Providers>
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </Providers>
        )}
      </body>
    </html>
  );
}
